services:
  postgres_db:
    image: postgres:16.2
    environment:
      POSTGRES_USER: tpf_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: polls
      PGDATA: /data/postgres
    volumes:
      - ./postgres_data:/data/postgres
    ports:
      - "5432:5432"
  http_java:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - "8080:8080"
    depends_on:
      - postgres_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/polls
      - SPRING_DATASOURCE_USERNAME=tpf_user
      - SPRING_DATASOURCE_PASSWORD=password
    command: sh -c "sleep 10 && java -jar /app/application.jar"